### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rajivcla**
I created a pr to your dev branch. i dont' have merge privilege

### CODE REVIEW

**Comment by b-maslennikov** [comment]
I'll fix AppVeyour and deploy next package version soon

**Comment by b-maslennikov** [comment]
I'll fix AppVeyor and then I'll deploy the package to Nuget
Thx

**Comment by b-maslennikov** [comment]
1.1.0 is released on Nuget.org

**Comment by rajivcla** [comment]
Thanks!

**Pull request merged**
