### PR TITLE
Update CSVHelper and net versions

### PR DESCRIPTION
**Pull request by rajivcla**
Hi b-maslennikov, I upgraded .NET versions and CSVHelper version

### CODE REVIEW

**Comment by b-maslennikov** [comment]
Hi @rajivcla 
What the reason to update CsvHelper up to v30? Was there a critical bug in v23?

**Comment by rajivcla** [comment]
Hi, there were breaking changes in the API to use CsvHelper from v23 to v30

**Comment by b-maslennikov** [comment]
what about the targets?

**Comment by b-maslennikov** [comment]
Could you please recreate this PR but in dev branch?

**Pull request closed without merging**
